"""Host Agent factory — creates one agent per host from output/agents/host-{slug}.md.

Each host file is generated by the show-setup workflow and contains the full
personalised character definition (persona, background, opinions, quirks,
catchphrases). No placeholder substitution is needed at runtime.
"""

import re
import sys
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[5]
if str(WORKSPACE) not in sys.path:
    sys.path.insert(0, str(WORKSPACE))

from utils.agents import create_agent, AgentOptions  # noqa: E402

AGENTS_DIR = WORKSPACE / "output" / "agents"


def _host_slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def parse_host_names(show_context: str) -> list[str]:
    """Extract host names from the ### Name sections in show_context.md."""
    names = []
    for section in re.split(r"^### (.+)$", show_context, flags=re.MULTILINE)[1::2]:
        name = section.strip()
        # Skip sections that aren't host entries (e.g. Episode History sub-headers)
        if name and not name.startswith("Episode"):
            names.append(name)
    return names


def create_host_agents(show_context: str) -> list[tuple[str, object]]:
    """Return a list of (host_name, agent) tuples, one per host in show_context."""
    agents = []
    for name in parse_host_names(show_context):
        slug = _host_slug(name)
        host_file = AGENTS_DIR / f"host-{slug}.md"
        if not host_file.exists():
            raise FileNotFoundError(
                f"Host agent file not found: {host_file}\n"
                f"Re-run the show setup workflow to regenerate output/agents/."
            )
        instructions = show_context + "\n\n---\n\n" + host_file.read_text()
        agent = create_agent(AgentOptions(
            name=f"Host_{name}",
            instructions=instructions,
        ))
        agents.append((name, agent))
    return agents
