"""Host Agent factory — creates one agent per host from output/agents/host-{slug}.md.

Each host file is generated by the show-setup workflow and contains the full
personalised character definition (persona, background, opinions, quirks,
catchphrases). No placeholder substitution is needed at runtime.
"""

import re
import sys
from pathlib import Path

WORKSPACE = Path(__file__).resolve().parents[4]
if str(WORKSPACE) not in sys.path:
    sys.path.insert(0, str(WORKSPACE))

from utils.agents import create_agent, AgentOptions  # noqa: E402

AGENTS_DIR = WORKSPACE / "output" / "agents"
CONVERSATION_STYLE_FILE = AGENTS_DIR / "conversation-style.md"


def _host_slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def parse_host_names(show_context: str) -> list[str]:
    """Extract host names from the ### Name sections within the ## Hosts block."""
    hosts_match = re.search(r"^## Hosts\s*\n(.*?)(?=^## |\Z)", show_context, flags=re.MULTILINE | re.DOTALL)
    if not hosts_match:
        return []
    hosts_section = hosts_match.group(1)
    return [s.strip() for s in re.split(r"^### (.+)$", hosts_section, flags=re.MULTILINE)[1::2] if s.strip()]


def create_host_agents(show_context: str) -> list[tuple[str, object]]:
    """Return a list of (host_name, agent) tuples, one per host in show_context."""
    agents = []
    for name in parse_host_names(show_context):
        slug = _host_slug(name)
        host_file = AGENTS_DIR / f"host-{slug}.md"
        if not host_file.exists():
            raise FileNotFoundError(
                f"Host agent file not found: {host_file}\n"
                f"Re-run the show setup workflow to regenerate output/agents/."
            )
        instructions = show_context + "\n\n---\n\n" + host_file.read_text()
        agent = create_agent(AgentOptions(
            name=f"Host_{name}",
            instructions=instructions,
        ))
        agents.append((name, agent))
    return agents


def create_recording_host_agents(show_context: str) -> list[tuple[str, object]]:
    """Return a list of (host_name, agent) tuples using the recording-mode host files.

    Loads host-{slug}-recording.md instead of host-{slug}.md so hosts output
    structured ---UTTERANCE--- blocks during a live recording session.

    If output/agents/conversation-style.md exists it is appended to every host's
    instructions so all hosts share the same naturalness guidelines.
    """
    conversation_style = (
        "\n\n---\n\n" + CONVERSATION_STYLE_FILE.read_text()
        if CONVERSATION_STYLE_FILE.exists()
        else ""
    )
    agents = []
    for name in parse_host_names(show_context):
        slug = _host_slug(name)
        host_file = AGENTS_DIR / f"host-{slug}-recording.md"
        if not host_file.exists():
            raise FileNotFoundError(
                f"Recording host agent file not found: {host_file}\n"
                f"Expected a -recording.md variant alongside the standard host file."
            )
        instructions = show_context + "\n\n---\n\n" + host_file.read_text() + conversation_style
        agent = create_agent(AgentOptions(
            name=f"Host_{name}_Recording",
            instructions=instructions,
        ))
        agents.append((name, agent))
    return agents
